# Generated by Django 4.1.6 on 2023-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=2)),
                ('word_original', models.CharField(max_length=64)),
                ('target_language', models.CharField(max_length=2)),
                ('word_translation', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('user_first_name', models.CharField(max_length=64)),
            ],
        ),
    ]
