# Generated by Django 4.1.6 on 2023-02-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_origin', to='chat.tests')),
                ('word', models.ManyToManyField(blank=True, related_name='tests_included', to='chat.newwords')),
            ],
        ),
    ]
