# Generated by Django 4.1.6 on 2023-02-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='word',
        ),
        migrations.AddField(
            model_name='testresult',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests_included', to='chat.newwords'),
        ),
    ]
